### PR TITLE
Handle empty blocks when decompressing DEFLATE streams.

### PR DESCRIPTION
**Pull request by tobz**
Trying to read an empty block triggers an error when reaching into the block to copy it to the output buffer.  Since some implementations, like Go, will generate empty static blocks as a way to end an output stream, we simply check to see if the block has any data.  If it does not, we simply proceed without attempting to copy the block contents.

### CODE REVIEW

**Comment by tobz** [comment]
Looking for thoughts on my copypasta job WRT `test_decode_pure`: Go generates an already "pure" DEFLATE output, so rather than special casing or shoving the `fixup` call a a wrapper around `include_bytes!`... I just decided to copypasta and be done with it.

**Comment by tobz** [comment]
Examples of what Go is doing (even thought there's a test case file for this now):

    000000 00 0b 00 f4 ff 68 65 6c 6c 6f 20 77 6f 72 6c 64
    0000010 00 00 00 ff ff 01 00 00 ff ff
    000001a

Static block (not EOF), then an empty static block (not EOF), and a final static block (EOF).

**Comment by tobz** [comment]
Where this was breaking before:

       474 	        let n = cmp::min(buf.len(), self.block.len() - self.pos);
       475 	        unsafe { copy_nonoverlapping(
    -> 476 	            &self.block[self.pos],
       477 	            &mut buf[0],
       478 	            n
       479 	        )};

with an error of:

    thread 'flate::test::decode' panicked at 'index out of bounds: the len is 0 but the index is 0', src/libcollections/vec.rs:1178

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
