### PR TITLE
Better package info

### PR DESCRIPTION
**Pull request by kvark**
Also, it would be great to have cargo publishing rights.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Will do!

**Comment by kvark** [comment]
Thanks @alexcrichton !

**Comment by alexcrichton** [comment]
Oh it looks like I haven't actually published this crate on crates.io yet (wasn't quite sure about the nice name but not-so-great perf), but feel free to publish!

**Comment by kvark** [comment]
Ouch, the [compress](https://crates.io/crates/compress) on crates.io is not rust-compress :(

**Comment by kvark** [comment]
@mahkoh Can we the `compress` crate?

**Comment by mahkoh** [comment]
I've added you as an owner.

**Comment by kvark** [comment]
@mahkoh Thanks! Greatly appreciated!
Do you mind if we remove you from the owners?

**Pull request merged**
